13 Technical Specification/1-я итерация
LipatovKir/java-shareit pull request #1
Opened 2023-06-24 18:48 UTC by LipatovKir

2023-06-25 09:25 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев, жду новую версию.

2023-06-25 09:25 UTC, Frilock commented on pom.xml
> +			<version>1.4.1</version>
Обсуждали вроде, что версию нужно в properties указывать

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +
Лишняя пустая строка

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/errorhandler/ErrorResponse.java
> +    String error;
Отсутствуют модификаторы, кроме того, можете воспользоваться аннотация от lombok

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto updateItem(@Validated({Update.class})
Нужно аннотацию на уровень класса добавить

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public static final String OWNER_NOT_FOUND = "Не найден владелец c id: ";
А она точно public нужна?

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!ownerExists) {
Бросок исключения проще перенести в сам метод isOwnerExists

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text == null || text.isBlank()) {
Лучше воспользоваться StringUtils.isBlank от apache common 3, там довольно много функций

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
ПРинято выражения писать в таком виде - 
stream()
.filter
.collect

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +            if ((itemName.contains(searchItem) || itemDescription.contains(searchItem))
StringUtils.containsIgnoreCase

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                    && item.getAvailable().equals(true)) {
BooleanUtils.isTrue

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (description != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
Блок else не нужен, можете код писать без него

2023-06-25 09:25 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
блок else не нужен

2023-06-25 09:41 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/model/BookingStatus.java
> +
исправил

2023-06-25 09:46 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/errorhandler/ErrorResponse.java
> +    String error;
исправил

2023-06-25 09:49 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public static final String OWNER_NOT_FOUND = "Не найден владелец c id: ";
исправил

2023-06-25 09:52 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<User> result = users.stream().filter(user -> user.getId() == ownerId).collect(Collectors.toList());
исправил

2023-06-25 09:55 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
исправлено

2023-06-25 09:55 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +        } else {
исправлено

2023-06-25 10:07 UTC, LipatovKir commented on pom.xml
> +			<version>1.4.1</version>
исправил

2023-06-25 10:14 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text == null || text.isBlank()) {
исправил

2023-06-25 11:00 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +            if ((itemName.contains(searchItem) || itemDescription.contains(searchItem))
исправил, использовал StringUtils.containsOnly.  с StringUtils.containsIgnoreCase не все запросы корректно обрабатывались

2023-06-25 11:04 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                    && item.getAvailable().equals(true)) {
исправил

2023-06-25 11:33 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (description != null) {
исправил

2023-06-26 05:37 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto updateItem(@Validated({Update.class})
добавил

2023-06-26 06:31 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (!ownerExists) {
исправил

2023-06-26 16:55 UTC, Frilock approved these changes
Принято

2023-07-03 05:57 UTC, merged