Add bookings
LipatovKir/java-shareit pull request #17
Opened 2023-07-14 06:49 UTC by LipatovKir

2023-07-15 17:41 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев к работе:
1. Следите за вложенностью в коде
2. Нет смысла ставить аннотации над интерфейсами
3. Детализируйте логгирование и броски исключений
4. Другие комментарии

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        log.info("Пользователь создал новое бронирование");
Кажется что нужно добавить больше информации в лог, хотя бы идентификатор

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
публичная схема является значением по умолчанию, можно не указывать ее. Вообще IDEA серым должна подсвечивать. Кроме того, не знаю говорил или нет, но предлагаю установить плагин sonarlint - статический анализатор кода, подскажет ряд хороших практик

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +    REJECTED;
; не нужна

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
Смотрите, над интерфейсами нет смысла ставить аннотации помечающих класс бином, главное чтоб аннотация стояла над реализацией данного интерфейса.

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            User user = userRepository.findById(userId).get();
Запрос делаете  userRepository.findById(userId) 2 раза. Делайте запрос до if, сохраняйте в переменную, а потом уже используйте

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (Boolean.FALSE.equals(item.getAvailable())) {
Можно BooleanUtils.IsFalse

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (itemRepository.findById(bookingDto.getItemId()).isPresent() || userRepository.findById(userId).isPresent()) {
Можно отказаться от лишней вложенности, инвертировав условие

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (booking.getStatus().equals(BookingStatus.APPROVED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BookingNotFoundException("Такая бронь не найдена");
Хочется видеть в ошибке так же идентификаторы данных или какие то другие данные, чтобы быстрее ее локализовать

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private State validateState(String state) {
Этот метод проситься в State

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Не нужно проверить, что заполнена?

2023-07-15 17:41 UTC, Frilock commented on src/main/resources/application.properties
> +
Много лишних пустых строк в конце файла

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +@Repository
Лишняя аннотация

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(name = "email", unique = true)
Смотрите, вы в скриптах указываете размерность поля, проставляйте ее также в анннотации Column, используя флаг lenght, чтобы не приходилось лишний раз лазить в скрипты

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
Лишняя аннотация

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Item item = itemRepository.findById(itemId).get();
itemRepository.findById(itemId) делайте до if

2023-07-15 17:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (!commentList.isEmpty()) {
Кусок в 2х местах повторяется, попробуйте в приватный метод вынести

2023-07-16 05:21 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        log.info("Пользователь создал новое бронирование");
исправил

2023-07-16 05:24 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
Да, я работаю с этим плагином, классная штука. Спасибо. Удалил Паблик, но он мне не подсветил этот момент.

2023-07-16 05:25 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +    REJECTED;
исправил

2023-07-16 05:27 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +@Repository
исправил

2023-07-16 05:51 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            if (Boolean.FALSE.equals(item.getAvailable())) {
исправил

2023-07-16 06:48 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                if (booking.getStatus().equals(BookingStatus.APPROVED)) {
исправил

2023-07-16 06:51 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +@Repository
исправил

2023-07-16 08:37 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            User user = userRepository.findById(userId).get();
я переделал этот метод с использованием .orElseThrow(), на мой взгляд стало лучше, надеюсь Вы его тоже согласуете.

2023-07-16 08:38 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/model/State.java
> +    REJECTED;
Оставил, метод добавил по валидации

2023-07-16 08:44 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (itemRepository.findById(bookingDto.getItemId()).isPresent() || userRepository.findById(userId).isPresent()) {
исправил метод

2023-07-16 08:49 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BookingNotFoundException("Такая бронь не найдена");
исправил

2023-07-16 08:49 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    private State validateState(String state) {
исправил

2023-07-16 08:51 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
исправил

2023-07-16 09:22 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +@Repository
исправил

2023-07-16 09:35 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(name = "email", unique = true)
исправил

2023-07-16 11:00 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getName() != null) {
исправил

2023-07-16 11:10 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Item item = itemRepository.findById(itemId).get();
переделал метод с использованием orElseThrow() и orElse, смотрится более читаемым.

2023-07-16 11:26 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (!commentList.isEmpty()) {
исправил

2023-07-16 11:45 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
LocalDateTime created заполняется автоматически при создании комментария, поэтому на мой взгляд проверка не нужна.

2023-07-16 12:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
Еще как вариант установите JPA Baddy

2023-07-16 12:37 UTC, Frilock approved these changes
Принято, хорошо. Еще советую поставить JPA Buddy плагин, тоже ряд хороших вещей подскажет.

2023-07-16 12:37 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (Boolean.TRUE.equals(approved)) {
Можно BooleanUtils.isTrue

2023-07-16 12:52 UTC, merged