Add item requests
LipatovKir/java-shareit pull request #18
Opened 2023-07-19 20:08 UTC by LipatovKir

2023-07-22 18:19 UTC, Frilock requested changes
Добрый вечер, в целом все ок, смущают только equals методы в классах моделях, не очень понятно почему они такого вида.

2023-07-22 18:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
Необычный equals, для чего так сложно делаете?

2023-07-22 18:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +
Куча лишних строчек в конце класса, уберите их

2023-07-22 18:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +
Лишние строки в конце файла

2023-07-22 18:19 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public static final String X_SHARER_USER = "X-Sharer-User-Id";
У вас в константах есть такая константа

2023-07-23 06:08 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
Ранее я использовал аннотации в ENTITY @DATA и @EqualsAndHashCode(onlyExplicitlyIncluded = true) но плагин JPA Buddy , который Вы посоветовали, мне их подсветил с указанием, что их лучше не использовать для объектов JPA из-за возможных проблем с памятью и производительностью. Добавлена фактическая проверка классов, Если объекты являются прокси-объектами Hibernate (HibernateProxy), то для получения фактического класса используется метод getPersistentClass() из HibernateLazyInitializer. . Это позволяет корректно сравнивать объекты и избегать проблем сравнения прокси-объектов с фактическими классами. Прошу одобрить оставить в таком виде.

2023-07-23 06:14 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +
исправил

2023-07-23 06:14 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +
исправил

2023-07-23 07:32 UTC, LipatovKir commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public static final String X_SHARER_USER = "X-Sharer-User-Id";
решил вынести отдельно, и не использовать ее из тестов, чтобы не пересекать приложение с тестами

2023-07-23 12:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public static final String X_SHARER_USER = "X-Sharer-User-Id";
Не обратил внимание, что константы в тестах находятся

2023-07-23 12:32 UTC, Frilock approved these changes
Принято, хорошая работа. Близки к завершению курса

2023-07-23 16:26 UTC, merged