Add docker
LipatovKir/java-shareit pull request #26
Opened 2023-08-05 12:41 UTC by LipatovKir

2023-08-07 06:00 UTC, Frilock requested changes
Добрый день, указал ряд комментариев, посмотрите, пожалуйста.

2023-08-07 06:00 UTC, Frilock commented on docker-compose.yml
> +  #    - TZ=Europe/Moscow
Лучше закомментированный код убрать

2023-08-07 06:00 UTC, Frilock commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Данной зависимости в модуле server быть не должно. Валидация входных данных только на gateway

2023-08-07 06:00 UTC, Frilock commented on server/pom.xml
> +            <version>20.1.0</version>
Версии библиотек, как минимум, нужно перенести в properties. Кроме того, вообще в многомодульных проектах точкой добавления зависимостей принято делать корневой пом файл. В нем нужно сделать блок dependencyManager и добавить туда библиотеки (для которых вы указываете версию), после чего в другие пом файлы вы можете их добавлять без указания версии (она будет подтягиваться из корневого). Попробуйте

2023-08-07 18:36 UTC, LipatovKir commented on docker-compose.yml
> +  #    - TZ=Europe/Moscow
Убрал. Поясню почему не сделал это ранее: тесты на Postman проходят только с указанием временной зоны, а на GitHub без указания. Как понял, если не указывать временную зону, то Docker устанавливает по умолчанию Гринвич.

2023-08-07 18:43 UTC, LipatovKir commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Удалил.

2023-08-08 00:17 UTC, LipatovKir commented on server/pom.xml
> +            <version>20.1.0</version>
Иван, спасибо за ревью и интересную задачу. Благодаря Вам, ищу новые решения и тем самым погружаюсь в изучение новых для себя тем.

2023-08-08 06:12 UTC, Frilock approved these changes
Принято, хорошо, успехов на дипломной работе

2023-08-08 06:12 UTC, Frilock commented on server/pom.xml
> +            <version>${spring.version}</version>
Тут по идее тоже можно без указания версии, если она в dependencyManager указана

2023-08-08 06:39 UTC, LipatovKir commented on server/pom.xml
> +            <version>${spring.version}</version>
Спасибо! это исправил.

2023-08-08 06:42 UTC, merged